apiVersion: v1
kind: Pod
metadata:
  name: mqtt-simulator
  namespace: default
spec:
  containers:
    - name: mqtt-simulator
      image: charrisagoracr.azurecr.io/mqtt-simulator
      resources: {}
  imagePullSecrets:
    - name: charrisagoracr
