apiVersion: v1
kind: Pod
metadata:
  name: mqtt-broker
  namespace: default
spec:
  containers:
    - name: mqtt-broker
      image: charrisagoracr.azurecr.io/mqtt-broker:latest
      # - image: 10.0.0.172:5000/mqtt-broker:latest
      ports:
        - containerPort: 1883
      resources: {}
  imagePullSecrets:
    - name: charrisagoracr
