apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mqtt-broker
  name: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mqtt-broker
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: mqtt-broker
    spec:
      containers:
        - image: charrisagoracr.azurecr.io/mqtt-broker:latest
        # - image: 10.0.0.172:5000/mqtt-broker:latest
          name: mqtt-broker
          ports:
            - containerPort: 1883
          resources: {}
      restartPolicy: Always
status: {}
